oracle/tribuo

Data/src/main/java/org/tribuo/data/csv/CSVIterator.java
Data/src/test/java/org/tribuo/data/csv/CSVIteratorTest.java
Data/src/test/resources/org/tribuo/data/csv/test-double-line-break.csv

Which would be fine (as it's not really to spec) if it wasn't for the fact that some datasets (like the Irises we use in the tutorial) come with a double new line at the end.
This patch treats a double newline as the end of the file. Previously if it was in the middle of the file it would cause it to error out, and if it was the end of the file it would also error out.

CSVLoader errors on double newlines at the end of files

---

docs/PackageOverview.md

The regression table was missing the last vertical pipe.

Fixed table markdown in PackageOverview.md

---

.github/workflows/maven-windows.yml
Classification/Explanations/pom.xml
Classification/XGBoost/pom.xml
Common/XGBoost/pom.xml
Regression/XGBoost/pom.xml
pom.xml

The XGBoost 1.0.0 binary on Maven Central doesn't have a Windows dll in it. This PR skips the XGBoost tests in the Windows CI until we upgrade to an XGBoost version which does have a Windows binary.

Skipping the XGBoost tests on Windows in Github Actions.

---

.github/workflows/maven-macos.yml
.github/workflows/maven-ubuntu.yml
.github/workflows/maven-windows.yml

Bumps the CI to test on 8, 11 and 15 from 8, 11 and 14.
We test on LTS and latest.

Bump OpenJDK 14 to 15 in Github Actions

---

Classification/XGBoost/src/test/java/org/tribuo/classification/xgboost/TestXGBoost.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostExternalModel.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostFeatureImportance.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostModel.java

Adding richer feature importance support to XGBoost modeling to get parity with other XGBoost wrappers.

Added support for full set of XGBoost feature importance metrics

---

Classification/Explanations/src/main/java/org/tribuo/classification/explanations/lime/LIMEColumnar.java
Data/src/main/java/org/tribuo/data/columnar/ColumnarDataSource.java
Data/src/main/java/org/tribuo/data/columnar/ResponseProcessor.java
Data/src/main/java/org/tribuo/data/columnar/RowProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/field/RegexFieldProcessor.java
Data/src/test/java/org/tribuo/data/csv/CSVDataSourceTest.java
Data/src/test/resources/org/tribuo/data/csv/test-regexmapping.csv

Fixes `ColumnarDataSource` and children not correctly calling `RowProcessor.expandRegexMapping` to support dynamic regex field headers.

Fixes `ColumnarDataSource` expandRegex issue

---

Data/src/main/java/org/tribuo/data/columnar/ColumnarDataSource.java
Data/src/main/java/org/tribuo/data/columnar/RowProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/BinaryResponseProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/FieldResponseProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/QuartileResponseProcessor.java
Data/src/test/java/org/tribuo/data/columnar/MockResponseProcessor.java

The current provenance code in `RowProcessor` looks at fields marked `@Config`, however the store of reference for field processors is not the `@Config` field `fieldProcessorList`, it's `fieldProcessorMap`. So when the regex field mapping is expanded the new field processors need to be written into both `fieldProcessorList` and `fieldProcessorMap` as the regex mapping is cleared.
It could go either way with this fix, either keep the regexes in the provenance, or only store the matched fields. The latter has better fidelity at replicating the model, because otherwise new fields could be matched by the regex (however that may be what the user wants). To preserve the flexibility the RowProcessor should be reinstantiated from it's original configuration if the user wants to have the regexes …

Capturing the provenance for RowProcessor's regex mapped fields

---

Core/src/main/java/org/tribuo/datasource/IDXDataSource.java
Core/src/test/java/org/tribuo/datasource/IDXDataSourceTest.java
Core/src/test/resources/org/tribuo/datasource/config.xml

If the idx files passed into `IDXDataSource` don't exist then it throws a random looking `NullPointerException` out of readData. This obscures what's actually going wrong, and it really should throw `FileNotFoundException`, so now it does.
Fixes the error message in #58 .

Makes IDXDataSource throw FileNotFoundException when the files don't exist

---

Regression/Core/src/main/java/org/tribuo/regression/ImmutableRegressionInfo.java

The domain was being stored as a TreeSet. TreeSet will hold on to its comparator when serialized, but the comparator was not (and should not be) serializable. Domain for ImmutableRegressionInfo is now stored as a LinkedHashSet to preserve sorted order without preserving the sorting semantics.
Fixes #67

Fix serialization for Regression models

---

Classification/DecisionTree/src/main/java/org/tribuo/classification/dtree/CARTClassificationTrainer.java
Classification/DecisionTree/src/main/java/org/tribuo/classification/dtree/impl/ClassifierTrainingNode.java
Common/Trees/src/main/java/org/tribuo/common/tree/AbstractCARTTrainer.java
Common/Trees/src/main/java/org/tribuo/common/tree/AbstractTrainingNode.java
Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/CARTJointRegressionTrainer.java
Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/CARTRegressionTrainer.java
Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/impl/JointRegressorTrainingNode.java
Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/impl/RegressorTrainingNode.java

Save Computation in Known Leaf Nodes - makes leaf nodes immediately instead of creating TrainingNodes first and then converting them to LeafNodes. 
Fix minChildWeight bug - minChildWeight was previously being compared to the unweighted number of examples, but will now correctly be compared to the sum of weighted examples.
Save computation. Fix a bug.

Save Computation in Known Leaf Nodes, Fix minChildWeight bug

---

Data/src/main/java/org/tribuo/data/csv/CSVDataSource.java
Data/src/main/java/org/tribuo/data/csv/CSVIterator.java
Data/src/main/java/org/tribuo/data/csv/CSVLoader.java
Data/src/test/java/org/tribuo/data/csv/CSVDataSourceTest.java
Data/src/test/java/org/tribuo/data/csv/CSVLoaderTest.java
Data/src/test/resources/org/tribuo/data/csv/test-bom.csv

This change reads the first few bytes into a `PushbackReader`, checks if they are a byte order mark for UTF-8 and discards them if they are. If they are regular bytes they are pushed back onto the reader and loading proceeds as normal.
The UTF-8 byte order mark is unnecessary as UTF-8 doesn't have ordered bytes. Tribuo doesn't support non-UTF-8 file formats in it's data loading.
If there is a byte order mark in a UTF-8 CSV file (as frequently inserted by Microsoft Excel), then OpenCSV will stitch it to the front of the first column, causing the name based parsing in `RowProcessor` among other places to fail. OpenCSV doesn't ignore these by default (unlike other CSV parsers) so here we patch the reader to do so.
Fixes #65.

Ignore a UTF-8 byte order mark in the csv package

---

Data/src/main/java/org/tribuo/data/columnar/extractors/DateExtractor.java
Data/src/main/java/org/tribuo/data/columnar/extractors/OffsetDateTimeExtractor.java
Data/src/test/java/org/tribuo/data/columnar/RowProcessorTest.java

Adds a `FieldExtractor` that can process date times to go with the one that can process dates. This one uses `OffsetDateTime` to capture timezone information. It's possible we'll need a `LocalDateTime` one for fields without time zone information as `OffsetDateTime` requires it and will fail to parse otherwise.
Also it deprecates the `DateExtractor` constructor which accepts a `DateTimeFormatter` as it's not possible to recover the format string out of such an object, and so the provenance isn't convertible into a configuration. It does however add the toString of the formatter which should be useful for figuring out what the original date format string was even if it can't be automatically generated.
Fixes a bug in the `DateExtractor`s provenance and adds a timestamp capability to the …

Adding an OffsetDateTimeExtractor, deprecating a DateExtractor constructor

---

pom.xml

Bumps OLCUT to 5.1.5 to bring in a provenance fix. This also bumps the version of Jackson used to 2.11.3 from 2.11.2, and the version of jline3 from 3.15.0 to 3.16.0.

Bumping OLCUT to 5.1.5.

---

Common/LibLinear/src/main/java/org/tribuo/common/liblinear/LibLinearModel.java
Common/LibSVM/src/main/java/org/tribuo/common/libsvm/LibSVMModel.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostExternalModel.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostFeatureImportance.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostModel.java

LibLinear, LibSVM and XGBoost all have internal model representations which Tribuo hides. This PR adds an accessor which returns a deep copy of the trained models allowing users to use them outside of Tribuo.
LibSVMModel has exposed the internal models for a while, this change makes it return an unmodifiable copy of the internal models (as the svm_model class is mutable for some reason). It then adds similar methods to LibLinearModel and XGBoostModel as it seems unfair to not allow it everywhere. We could further allow people to load in externally trained LibSVM and LibLinear models, and easily test it using this support, but it's not clear if there is need for such support at the moment.
Fixes #78.

Adds a getter which returns a copy of the inner model

---

AnomalyDetection/LibSVM/src/main/java/org/tribuo/anomaly/libsvm/LibSVMAnomalyTrainer.java
Classification/LibSVM/src/main/java/org/tribuo/classification/libsvm/LibSVMClassificationTrainer.java
Common/LibSVM/src/main/java/org/tribuo/common/libsvm/LibSVMTrainer.java
Regression/LibSVM/src/main/java/org/tribuo/regression/libsvm/LibSVMRegressionTrainer.java

The train methods on LibSVMTrainer mutated the state of the svm_parameters struct if gamma was zero (it's a sentinel to set the value to 1.0/numFeatures), but this isn't necessarily the parameters that are passed in (e.g. if label weights are used). This mutation also causes it to ignore the number of features in a second call to train as gamma is already non-zero. This is fixed by making each training run get a fresh set of the parameters.
Trainers should track their state properly and not mutate their parameters (except for the RNG, and we track that in the provenance system).

LibSVMTrainer was insufficiently immutable

---

tutorials/configuration/example-config.xml

The example xml file for the tutorial has the wrong type for the MNIST test datasource. This PR fixes it.

Fixing a bug in the configuration tutorial example XML file.

---

tutorials/anomaly-tribuo-v4.ipynb
tutorials/clustering-tribuo-v4.ipynb
tutorials/columnar-tribuo-v4.ipynb
tutorials/configuration-tribuo-v4.ipynb
tutorials/external-models-tribuo-v4.ipynb
tutorials/irises-tribuo-v4.ipynb
tutorials/regression-tribuo-v4.ipynb

Updating the version to the Tribuo JAR files in the Java-based tutorials to bring them in sync with the recently released 4.0.2 version
Also fixed JavaDoc links in the Regression Tutorial.
Raised as a fix on the back of #92

Tutorials: updating the version to the Tribuo JAR files in the respective cells

---

Interop/ONNX/pom.xml
pom.xml

Adds a flag to the pom file which quiesces the ONNX tests.
The ONNX tests don't pass on Apple Silicon as I've only just added the support for it to the upstream release.

Add an option to quiesce ONNX tests

---

Clustering/KMeans/src/main/java/org/tribuo/clustering/kmeans/KMeansModel.java
Clustering/KMeans/src/main/java/org/tribuo/clustering/kmeans/KMeansTrainer.java
tutorials/clustering-tribuo-v4.ipynb

Adds `KMeansModel.getCentroids` which returns a `List<List<Feature>>`. The old `getCentroidVectors` method requires the user to do the mapping from internal feature indices to feature names themselves, and the indices should never be required to use the library. I've updated the clustering tutorial to use the new method and also the K-Means++ initialisation added after the 4.0 release.
Adds the new centroid accessor. It also fixes a compatibility bug as `KMeansTrainer` had it's constructor changed in a backwards incompatible way, so a constructor with the correct signature was added.
This is an improvement discussed in #72.

Adds a better method for accessing the centroids of a KMeansModel

---

README.md

Adds a section describing the repository layout to the readme, along with a few clarifications to other sections.
Fixes #92 by describing our repo layout and why the tutorials use the Tribuo version number they do.

Adds a repository layout section to the main readme

---

Classification/DecisionTree/src/main/java/org/tribuo/classification/dtree/impl/ClassifierTrainingNode.java
Common/Trees/src/main/java/org/tribuo/common/tree/AbstractTrainingNode.java
Common/Trees/src/main/java/org/tribuo/common/tree/LeafNode.java
Common/Trees/src/main/java/org/tribuo/common/tree/SplitNode.java
Common/Trees/src/main/java/org/tribuo/common/tree/TreeModel.java
Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/IndependentRegressionTreeModel.java
Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/impl/JointRegressorTrainingNode.java
Regression/RegressionTree/src/main/java/org/tribuo/regression/rtree/impl/RegressorTrainingNode.java

Fixing an issue where classification trees split incorrectly, adding a method to get the depth of a built tree for debugging, renamed a couple of methods.
Classification trees mirrored the left indices into the right indices, so the trees were broken and performed poorly.

Fixing a classification tree bug

---

Data/src/main/java/org/tribuo/data/columnar/RowProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/EmptyResponseProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/package-info.java
Data/src/test/java/org/tribuo/data/columnar/processors/response/EmptyResponseProcessorTest.java

Adds a response processor which always returns an empty optional (i.e. no response). This is used by RowProcessors which operate on unlabelled data like clustering or anomaly detection tasks.
Also adds an additional constructor to `RowProcessor` to make it a little simpler to use.
Makes like simpler when loading clustering or anomaly detection columnar datasets.
Partial fix for #72.

Adding an empty response processor that always returns an empty optional

---

Core/src/main/java/org/tribuo/util/HTMLOutput.java
Core/src/main/java/org/tribuo/util/IntDoublePair.java
Core/src/main/java/org/tribuo/util/MeanVarianceAccumulator.java
Core/src/main/java/org/tribuo/util/Util.java
Core/src/test/java/org/tribuo/util/MeanVarianceAccumulatorTest.java
Data/src/main/java/org/tribuo/data/CompletelyConfigurableTrainTest.java
Regression/Core/config/example-datasource-config.xml
Regression/Core/src/main/java/org/tribuo/regression/ImmutableRegressionInfo.java
Regression/Core/src/main/java/org/tribuo/regression/MutableRegressionInfo.java
Regression/Core/src/main/java/org/tribuo/regression/evaluation/RegressionEvaluationImpl.java
Regression/Core/src/main/java/org/tribuo/regression/example/GaussianDataSource.java
Regression/Core/src/main/java/org/tribuo/regression/example/NonlinearGaussianDataSource.java
Regression/Core/src/main/java/org/tribuo/regression/example/RegressionDataGenerator.java
Regression/LibSVM/src/main/java/org/tribuo/regression/libsvm/LibSVMRegressionModel.java
Regression/LibSVM/src/main/java/org/tribuo/regression/libsvm/LibSVMRegressionTrainer.java
Regression/LibSVM/src/main/java/org/tribuo/regression/libsvm/TrainTest.java

Adds an option to LibSVMRegressionTrainer which standardises the input (i.e. ensures it's mean zero variance one) before training a model. It then applies the inverse transformation to the predictions to map them back into the correct output space. It also adds a non-linear regression data generator for testing, adds a couple of related methods in `org.tribuo.util.Util` and tidies up some related comments.
The internal implementation is quite ugly as it extends `svm_model` to poke in the mean and variance, because the types in the base `LibSVMTrainer` are too restrictive. When we have a breaking version it might be worth refactoring this and `LibLinearTrainer` (which is similar) to make the internal types controlled by Tribuo so they can be more easily extended if necessary (or just make …

Adds support for standardising regression values in LibSVM

---

pom.xml

Simple update from liblinear-java 2.42 to 2.43
Staying on the latest release. No new changes from 2.43 are actually required.

Updated liblinear-java to 2.43

---

Classification/XGBoost/src/main/java/org/tribuo/classification/xgboost/XGBoostClassificationTrainer.java
Classification/XGBoost/src/main/java/org/tribuo/classification/xgboost/XGBoostOptions.java
Classification/XGBoost/src/test/java/org/tribuo/classification/xgboost/TestXGBoost.java
Common/XGBoost/pom.xml
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostTrainer.java
Regression/XGBoost/src/main/java/org/tribuo/regression/xgboost/XGBoostRegressionTrainer.java
pom.xml

Bumps XGBoost from 1.0.0 to 1.3.2. Also plumbs through additional XGBoost parameters, so now the booster type and tree method are controllable. Exposes the logging verbosity as a replacement for the deprecated silent parameter.

Upgrades XGBoost to 1.3.1

---

Core/src/main/java/org/tribuo/Dataset.java
Core/src/main/java/org/tribuo/transform/TransformStatistics.java
Core/src/main/java/org/tribuo/transform/TransformTrainer.java
Core/src/main/java/org/tribuo/transform/TransformationMap.java
Core/src/main/java/org/tribuo/transform/TransformedModel.java
Core/src/main/java/org/tribuo/transform/TransformerMap.java
Core/src/main/java/org/tribuo/transform/package-info.java
Core/src/main/java/org/tribuo/transform/transformations/BinningTransformation.java
Core/src/main/java/org/tribuo/transform/transformations/IDFTransformation.java
Core/src/main/java/org/tribuo/transform/transformations/LinearScalingTransformation.java
Core/src/main/java/org/tribuo/transform/transformations/MeanStdDevTransformation.java
Core/src/main/java/org/tribuo/transform/transformations/SimpleTransform.java
Core/src/test/java/org/tribuo/transform/TransformationMapTest.java
Data/src/main/java/org/tribuo/data/columnar/processors/field/DoubleFieldProcessor.java

This PR adds implementations of `observeSparse` to all the transformers (apart from `IDFTransformation` which already had it). As a consequence to preserve the 4.0 behaviour the transformation fitting methods grow a new argument which turns on or off the use of the `observeSparse` method. It also switches `DoubleFieldProcessor` over so that it always emits values if they are parsable doubles. Before it would elide zero values, but this makes it much harder to implement transformations which should touch every value because they are numerical (rather than categorical encoded as a double).
One downside of this implementation is that it's not possible to change the behaviour of `observeSparse` on a per feature basis (due to it being a tricky breaking API change), which makes it difficult to …

Fixing the transformer behaviour on sparse features

---

Classification/Core/src/test/java/org/tribuo/classification/ensemble/VotingCombinerTest.java
Core/src/main/java/org/tribuo/ensemble/EnsembleModel.java
Core/src/main/java/org/tribuo/ensemble/WeightedEnsembleModel.java
Core/src/main/java/org/tribuo/provenance/impl/TimestampedTrainerProvenance.java
Regression/Core/src/test/java/org/tribuo/regression/ensemble/AveragingCombinerTest.java

This PR adds a method to `WeightedEnsembleModel` called `createEnsembleFromExistingModels` which builds an ensemble out of the supplied model list, ensemble combiner and optionally model combination weights. It adds a `TimestampTrainerProvenance` which is used as the `TrainerProvenance` for any ensembles created this way. Finally it adds a couple of tests for `VotingCombiner` and `AveragingCombiner` along with a few tests of the new behaviour.
The ensemble building mechanism validates that there are at least two models, that there are equal numbers of models and combination weights and that the output domains for all the supplied models are the same. We could consider adding a check that the feature domains are the same, or have some overlap, but it's plausible that text models trained …

Adds a way to create an ensemble out of existing models

---

Core/src/main/java/org/tribuo/datasource/AggregateConfigurableDataSource.java
Core/src/main/java/org/tribuo/datasource/AggregateDataSource.java
Core/src/main/java/org/tribuo/provenance/ModelProvenance.java
Core/src/test/java/org/tribuo/datasource/AggregateDataSourceTest.java
Core/src/test/java/org/tribuo/test/Helpers.java

Adds an enum to `AggregateDataSource` that lets users pick the iteration order. The two options are sequential, which was the old behaviour, where each internal data source is exhausted in sequence, or round robin which draws an example from each data source in turn.
Adds `AggregateConfigurableDataSource` which is the same as `AggregateDataSource` but can be configured.
There's also a slight refactor in the test helpers to expose provenance marshalling checks.
Building data sources from multiple files is a pain, and `AggregateDataSource` had slightly misleading documentation. This fixes the docs and makes it easier to aggregate things as they can be all placed in one config file.
Partial fix for #123 until we have a bigger refactor of file based data sources.

Allows configurable iteration order in AggregateDataSource, and adds a configurable version

---

pom.xml

OpenCSV 5.2 has a dependency conflict with itself (it pulls in two versions of Apache Commons Lang 3). This bumps the dependency to 5.4 which doesn't have the issue, and also adds the Maven Enforcer plugin to fix #131.
Depending on multiple versions of the same library is likely to cause trouble when deploying Tribuo, even if it's transitively.

Bump OpenCSV to 5.4

---

Core/src/main/java/org/tribuo/datasource/AggregateDataSource.java
Core/src/main/java/org/tribuo/provenance/ModelProvenance.java
pom.xml

Bumps OLCUT to 5.1.6 and migrates ModelProvenance.maybeExtractProvenance over to ObjectProvenance.maybeExtractProvenance.
Pulls in updated jline3 and jackson dependencies and a few OLCUT bug fixes.

Upgrades OLCUT to 5.1.6

---

.github/workflows/maven-windows.yml
Classification/XGBoost/src/main/java/org/tribuo/classification/xgboost/XGBoostClassificationTrainer.java
Classification/XGBoost/src/main/java/org/tribuo/classification/xgboost/package-info.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostExternalModel.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostModel.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostTrainer.java
Common/XGBoost/src/main/java/org/tribuo/common/xgboost/package-info.java
Regression/XGBoost/src/main/java/org/tribuo/regression/xgboost/XGBoostRegressionTrainer.java
Regression/XGBoost/src/main/java/org/tribuo/regression/xgboost/package-info.java
pom.xml

Bumps the XGBoost version to 1.4.1. This version has a bunch of native library improvements, the JVM library loader changes I wrote, a small improvement to XGBoost.loadModel, and a Windows binary in the Maven Central release. Turns on the XGBoost CI tests on Windows. I'll tidy up the XGBoost related tutorial text in the `4.1-tutorials` branch rather than induce more conflicts.
The Windows binary now means that Tribuo's tutorials will run on Windows as well as macOS and Linux x86_64 platforms.

Upgrading XGBoost to 1.4.1

---

Core/src/main/java/org/tribuo/impl/ArrayExample.java
Core/src/main/java/org/tribuo/impl/BinaryFeaturesExample.java
Core/src/test/java/org/tribuo/ExampleTest.java

ArrayExample.iterator and BinaryFeaturesExample.iterator used to throw ArrayIndexOutOfBoundsException rather than the expected NoSuchElementException when exhausted. Now they throw the correct exception.
The iterators should conform to the documentation for `java.util.Iterator`.

Fixing ArrayExample.iterator so it throws NoSuchElementException

---

Classification/SGD/src/main/java/org/tribuo/classification/sgd/linear/LinearSGDModel.java
Classification/SGD/src/test/java/org/tribuo/classification/sgd/linear/TestSGDLinear.java
Common/SGD/src/main/java/org/tribuo/common/sgd/AbstractLinearSGDModel.java
Common/SGD/src/main/java/org/tribuo/common/sgd/AbstractLinearSGDTrainer.java
Common/SGD/src/main/java/org/tribuo/common/sgd/AbstractSGDModel.java
Common/SGD/src/main/java/org/tribuo/common/sgd/AbstractSGDTrainer.java
Math/src/main/java/org/tribuo/math/FeedForwardParameters.java
Math/src/main/java/org/tribuo/math/LinearParameters.java
Math/src/main/java/org/tribuo/math/Parameters.java
MultiLabel/Core/src/test/java/org/tribuo/multilabel/IndependentMultiLabelTest.java
MultiLabel/SGD/src/main/java/org/tribuo/multilabel/sgd/linear/LinearSGDModel.java
MultiLabel/SGD/src/test/java/org/tribuo/multilabel/sgd/linear/TestSGDLinear.java
Regression/SGD/src/main/java/org/tribuo/regression/sgd/linear/LinearSGDModel.java
Regression/SGD/src/test/java/org/tribuo/regression/sgd/linear/TestSGDLinear.java

This PR extracts out `AbstractSGDModel` and `AbstractSGDTrainer` from `AbstractLinearSGDModel` and `AbstractLinearSGDTrainer`, and introduces a `FeedForwardParameters` which has predict and gradient methods. They don't land on `Parameters` because that's used in the CRF as well, and sequences have a differently shaped input.
`AbstractSGDTrainer` has a lot of generic parameters, but those are all hidden from users and the concrete subclasses are still typed with just the output type like most of Tribuo. The code is tested by the existing tests, and can still deserialize Tribuo 4.0 models.
The recent introduction of AbstractLinearSGDModel/Trainer wasn't quite abstract enough. The SGD package could be used for things beyond linear models like factorization machines. This PR will make it …

Refactoring AbstractLinearSGDModel and Trainer to extract SGD base classes

---

Common/SGD/src/main/java/org/tribuo/common/sgd/AbstractLinearSGDTrainer.java
Common/SGD/src/main/java/org/tribuo/common/sgd/AbstractSGDTrainer.java

The parameter creation hook in `AbstractSGDTrainer` now accepts a RNG to allow for random initialisations of the logistic regression and future trainers which depend on `AbstractSGDTrainer`.
Tribuo's linear sgd models use a fixed initialisation, but we're considering making it random. Some of the other SGD models we're investigating for the next release will need random initialisations for symmetry breaking, and so they need access to the localRNG produced for that call to train. The RNG state is already tracked in the trainer provenance so this change is very small.

Adding the RNG to AbstractSGDTrainer.createParameters()

---

docs/release-notes/tribuo-v4-0-1-release-notes.md
docs/release-notes/tribuo-v4-0-2-release-notes.md
docs/release-notes/tribuo-v4-0-release-notes.md

We're adding markdown versions of the Github release notes into the repo so they are always accessible.

Adding release notes for the earlier v4 releases

---

Classification/Core/src/test/java/org/tribuo/classification/ensemble/VotingCombinerTest.java
Core/src/main/java/org/tribuo/MutableDataset.java
Core/src/main/java/org/tribuo/provenance/EnsembleModelProvenance.java
Core/src/main/java/org/tribuo/util/Util.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/MultiLabel.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/BinaryExample.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/ClassifierChainModel.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/ClassifierChainTrainer.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/IndependentMultiLabelModel.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/IndependentMultiLabelTrainer.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/package-info.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/ensemble/CCEnsembleTrainer.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/ensemble/MultiLabelVotingCombiner.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/ensemble/package-info.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelEvaluation.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelEvaluationImpl.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelEvaluator.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelMetrics.java
MultiLabel/Core/src/test/java/org/tribuo/multilabel/baseline/ClassifierChainTest.java
MultiLabel/Core/src/test/java/org/tribuo/multilabel/baseline/IndependentMultiLabelTest.java
MultiLabel/Core/src/test/java/org/tribuo/multilabel/ensemble/CCEnsembleTest.java
MultiLabel/Core/src/test/java/org/tribuo/multilabel/ensemble/MultiLabelVotingCombinerTest.java
MultiLabel/Core/src/test/java/org/tribuo/multilabel/evaluation/MultiLabelEvaluatorTest.java
docs/Roadmap.md

Adds `ClassifierChainTrainer/Model`, and `CCEnsembleTrainer` which train classifier chains and an ensemble of classifier chains respectively. The ensemble required a multi-label voting combiner, which allows the use of bagging and RF in multi-label problems in Tribuo in addition to supporting classifier chain ensembles.
It also adds the jaccard score as a multi-label evaluation metric as it was useful while testing out this implementation.
As part of the work there is a small performance improvement to `IndependentMultiLabelTrainer` so it doesn't recreate the dataset for each label, and that trainer now correctly throws an exception if it is used inside `HashingTrainer` as the hashing mechanism interferes with the multi-label conversion mechanism. It is future work to make the two …

Adds classifier chains as a generic multi-label classifier

---

Data/src/main/java/org/tribuo/data/columnar/FieldProcessor.java
Data/src/main/java/org/tribuo/data/columnar/extractors/DateExtractor.java
Data/src/main/java/org/tribuo/data/columnar/extractors/OffsetDateTimeExtractor.java
Data/src/main/java/org/tribuo/data/columnar/processors/field/DateFieldProcessor.java
Data/src/test/java/org/tribuo/data/columnar/extractors/DateExtractorTest.java
Data/src/test/java/org/tribuo/data/columnar/extractors/OffsetDateTimeExtractorTest.java
Data/src/test/java/org/tribuo/data/columnar/processors/field/DateFieldProcessorTest.java

Adds a `FieldProcessor` which parses a date value into a variety of features.
This also adds a new `GeneratedFeatureType` as date values produce integer features, along with adding locale generation to `DateExtractor` and `OffsetDateTimeExtractor`.
Tribuo needs a way of using dates as features as well as example metadata.

Adds a field processor which operates on dates

---

Regression/Core/src/main/java/org/tribuo/regression/MutableRegressionInfo.java
pom.xml

XGBoost, ONNX and TF don't provide ARM binaries on Maven Central, so those tests need to be skipped on ARM platforms. This change makes it easier to do so.
It also removes a deprecation warning from `MutableRegressionInfo` which should have switched to using `UNKNOWN_REGRESSOR` when we added the deprecation notice to `UNKNOWN_MULTIPLE_REGRESSOR` in 4.1. Both fields refer to the same object, so there is no visible change.

Adding an ARM maven profile which skips the native library tests

---

Classification/Explanations/src/main/java/org/tribuo/classification/explanations/lime/LIMEExplanation.java
Classification/Explanations/src/test/java/org/tribuo/classification/explanations/lime/LIMEColumnarTest.java

SparseModels which only had a single feature set (rather than one per output dimension) caused an NPE in `LIMEExplanation.toString()` and other places which tried to use the output of `LIMEExplanation.getActiveFeatures()`.
LIME should work with any SparseTrainer, and the explanations should not throw NPE anywhere.
Noticed when looking at #156.

Fixing an NPE in LIMEExplanation.getActiveFeatures()

---

Data/src/main/java/org/tribuo/data/columnar/ColumnarFeature.java
Data/src/main/java/org/tribuo/data/columnar/processors/field/DoubleFieldProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/BinaryResponseProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/EmptyResponseProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/FieldResponseProcessor.java
Data/src/main/java/org/tribuo/data/columnar/processors/response/QuartileResponseProcessor.java
Data/src/main/java/org/tribuo/data/csv/CSVDataSource.java
Data/src/main/java/org/tribuo/data/csv/CSVLoader.java
Data/src/test/java/org/tribuo/data/columnar/MockResponseProcessor.java
Data/src/test/java/org/tribuo/data/columnar/processors/response/EmptyResponseProcessorTest.java
Data/src/test/java/org/tribuo/data/csv/CSVLoaderTest.java

This change rebases `CSVLoader` on top of `CSVDataSource`, instead of reading the CSVs itself and processing the examples into a `ListDataSource`. 
There are currently two breaking changes both of which are sufficiently minor that we're ok with introducing them in a minor release. 
- All the `CSVLoader.loadDataSource` overloads now return `DataSource<T>` rather than `ListDataSource<T>` and the source they return is an instance of `CSVDataSource<T>`. This is unavoidable unless we want to read the `CSVDataSource` directly into a `ListDataSource` on construction, which might cause provenance issues.
- `CSVLoader.loadDataSource` is now lazy, like `CSVDataSource` itself. Previously it used to read the whole csv file and buffer the examples in memory, triggering any parsing exceptions during …

CSVLoader refactor

---

AnomalyDetection/Core/src/main/java/org/tribuo/anomaly/example/AnomalyDataGenerator.java
AnomalyDetection/Core/src/main/java/org/tribuo/anomaly/example/GaussianAnomalyDataSource.java
AnomalyDetection/Core/src/main/java/org/tribuo/anomaly/example/package-info.java
AnomalyDetection/LibLinear/src/test/java/org/tribuo/anomaly/liblinear/LibLinearAnomalyTrainerTest.java
tutorials/anomaly-tribuo-v4.ipynb

Adds a configurable data source for anomaly detection demos and testing. Updated the anomaly detection tutorial to use it.
The reproducibility system we're adding in 4.2 should be able to reproduce all the tutorial models, and unfortunately several of those models are based on static data generators which would require special casing in the reproducibility system. Additionally those data generators aren't flexible enough to be useful demos or sufficiently complex to stress more complicated algorithms (both in terms of statistical complexity and runtime speed). This PR is the first in a series which will add configurable data sources which generate data for anomaly detection, clustering, multi-class classification and multi-label classification. We'll update some test code and any …

Adds a ConfigurableDataSource data generator for AnomalyDetection

---

AnomalyDetection/Core/src/main/java/org/tribuo/anomaly/example/GaussianAnomalyDataSource.java
Clustering/Core/src/main/java/org/tribuo/clustering/example/GaussianClusterDataSource.java
Clustering/Core/src/main/java/org/tribuo/clustering/example/package-info.java
Clustering/KMeans/src/test/java/org/tribuo/clustering/kmeans/TestKMeans.java
tutorials/clustering-tribuo-v4.ipynb

Adds a configurable data source for clustering demos and testing. Updated the clustering tutorial to use it.
The timing numbers are from my M1 Mac which is so fast that the multithreaded one takes roughly the same time as the single threaded one rather than being 3x faster (though it is running on 4x the data).
See #160 for the motivation.

Adds a ConfigurableDataSource data generator for Clustering

---

Classification/Core/src/main/java/org/tribuo/classification/example/CheckerboardDataSource.java
Classification/Core/src/main/java/org/tribuo/classification/example/ConcentricCirclesDataSource.java
Classification/Core/src/main/java/org/tribuo/classification/example/DemoLabelDataSource.java
Classification/Core/src/main/java/org/tribuo/classification/example/GaussianLabelDataSource.java
Classification/Core/src/main/java/org/tribuo/classification/example/InterlockingCrescentsDataSource.java
Classification/Core/src/main/java/org/tribuo/classification/example/NoisyInterlockingCrescentsDataSource.java
Classification/Core/src/main/java/org/tribuo/classification/example/package-info.java
Classification/Core/src/test/java/org/tribuo/classification/example/DemoLabelDataSourceTest.java

Adds 5 data generators for 2d binary classification problems suitable for classification demos & tutorials.
They are modelled on earlier Tribuo demo datasets but updated for the current API.
See #160 for motivation.

Adds ConfigurableDataSource data generators for Classification

---

AnomalyDetection/Core/src/main/java/org/tribuo/anomaly/example/GaussianAnomalyDataSource.java
Clustering/Core/src/main/java/org/tribuo/clustering/example/GaussianClusterDataSource.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/example/MultiLabelGaussianDataSource.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/example/package-info.java
Regression/Core/src/main/java/org/tribuo/regression/example/GaussianDataSource.java
Regression/Core/src/main/java/org/tribuo/regression/example/NonlinearGaussianDataSource.java
docs/Architecture.md
docs/FAQs.md
docs/PackageOverview.md
tutorials/README.md
tutorials/multi-label-tribuo-v4.ipynb

Adds a tutorial on multi-label problems showing the multi-label `LinearSGDTrainer`, the binary relevance based `IndependentMultiLabelTrainer`, a single classifier chain using `ClassifierChainTrainer`, and an ensemble of classifier chains using `CCEnsembleTrainer`. 
It also adds a configurable data source generator for multi-label data.
Note the configurable data source won't provenance correctly until Tribuo depends on a version of OLCUT with this PR merged (https://github.com/oracle/olcut/pull/37), and so it's not part of the unit tests yet.
We'd like tutorials for each prediction type in Tribuo and multi-label was the last type without a tutorial.
It also adds the last configurable data source needed to round out the set of demo sources for each prediction type (see …

Adds a tutorial on multi-label problems and a configurable data source generator for multi-label demos.

---

pom.xml

Bump LibSVM to 3.25.
Moving to LibSVM's latest version for compliance reasons (there are no Java fixes in this version vs 3.24 as far as I can tell).

Bumping LibSVM version

---

Classification/SGD/src/test/java/org/tribuo/classification/sgd/linear/TestSGDLinear.java
Core/src/main/java/org/tribuo/onnx/ONNXUtils.java
Core/src/main/java/org/tribuo/onnx/package-info.java
MultiLabel/SGD/src/test/java/org/tribuo/multilabel/sgd/linear/TestSGDLinear.java
Regression/Core/src/main/java/org/tribuo/regression/RegressionFactory.java
Regression/SGD/src/test/java/org/tribuo/regression/sgd/linear/TestSGDLinear.java
Regression/SLM/pom.xml
Regression/SLM/src/main/java/org/tribuo/regression/slm/SparseLinearModel.java
Regression/SLM/src/test/java/org/tribuo/regression/slm/TestSLM.java

Adds ONNX export support to `SparseLinearModel`, which covers `SLMTrainer`, `LARSTrainer`, `LARSLassoTrainer` and `ElasticNetCDTrainer`. Added a helper method to `ONNXUtils` which can convert a `double[]` into a float Tensor vector (unfortunately due to the packaging I can't add a `DenseVector` helper because it's not visible from tribuo-core).
Also added a check to the ONNX export tests to turn off the ORT bit on arm64 platforms as ORT doesn't have an arm64 binary in the published jar on Maven Central. The tests do pass on arm64 when ORT is compiled on arm64, so if MS add the binary to Maven Central we can remove this restriction.
Finally it also fixes a bug in `RegressionFactory.constructInfoForExternalModel` which previously couldn't construct infos for multidimensional regressions. …

Adds ONNX export support to the sparse linear models

---

MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelConfusionMatrix.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelEvaluationImpl.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelMetrics.java
MultiLabel/Core/src/test/java/org/tribuo/multilabel/evaluation/MultiLabelEvaluatorTest.java
MultiLabel/SGD/src/test/java/org/tribuo/multilabel/sgd/linear/TestSGDLinear.java

The multilabel evaluation package swapped the FPs for FNs when accessing them, causing many of the metrics to be permuted incorrectly producing incorrect values for precisions, recalls and the evaluation.toString().
It's best if the evaluations report the right numbers in the right places.

Fixing a bug where MultiLabelConfusionMatrix swapped FP for FN

---

Data/src/main/java/org/tribuo/data/csv/CSVDataSource.java
Data/src/main/java/org/tribuo/data/csv/CSVIterator.java
Data/src/test/java/org/tribuo/data/csv/CSVLoaderTest.java

The headers were set after the provenance was constructed, so the provenance only recorded headers set via configuration. This PR fixes that bug and adds a test for the behaviour. It also makes the CSVDataSource constructor which accepts headers public so it can be used by developers. An additional public constructor which accepts a header and a Path was added to maintain parity.
When using CSVLoader on a file without headers it should persist the headers in the provenance so the configuration is recoverable. Also the CSVDataSource constructor which accepts headers is generally useful if people wish to construct a CSVDataSource for csvs without headers manually.

CSVDataSource should persist the headers in the provenance

---

AnomalyDetection/LibLinear/src/main/java/org/tribuo/anomaly/liblinear/LibLinearAnomalyTrainer.java
AnomalyDetection/LibSVM/src/main/java/org/tribuo/anomaly/libsvm/LibSVMAnomalyTrainer.java
AnomalyDetection/LibSVM/src/main/java/org/tribuo/anomaly/libsvm/SVMAnomalyType.java
Classification/LibLinear/src/main/java/org/tribuo/classification/liblinear/LibLinearClassificationTrainer.java
Classification/LibLinear/src/test/java/org/tribuo/classification/liblinear/TestLibLinearModel.java
Classification/LibSVM/src/main/java/org/tribuo/classification/libsvm/LibSVMClassificationModel.java
Classification/LibSVM/src/main/java/org/tribuo/classification/libsvm/LibSVMClassificationTrainer.java
Classification/LibSVM/src/test/java/org/tribuo/classification/libsvm/TestLibSVM.java
Common/LibLinear/src/main/java/org/tribuo/common/liblinear/LibLinearTrainer.java
Common/LibSVM/src/main/java/org/tribuo/common/libsvm/LibSVMModel.java
Common/LibSVM/src/main/java/org/tribuo/common/libsvm/LibSVMTrainer.java
Regression/LibLinear/src/main/java/org/tribuo/regression/liblinear/LibLinearRegressionTrainer.java
Regression/LibSVM/src/main/java/org/tribuo/regression/libsvm/LibSVMRegressionTrainer.java

This change fixes Tribuo's LibLinear and LibSVM interfaces so they use trackable RNG states. 
LibLinear has a protected global RNG with a reset method (to a fixed seed), so now Tribuo sequentialises all LibLinear training runs under a lock on `LibLinearTrainer.class` and resets the seed before each call to `Linear.train`. There's a new reproducibility test in the classification LibLinear module which fails without these changes. This fix may change depending on the resolution of https://github.com/bwaldvogel/liblinear-java/issues/40.
LibSVM has a public global RNG so we use Tribuo's standard RNG idiom (a per train call `localRNG` split from the trainer's instance of `SplittableRandom`), LibSVM's global RNG's seed is set to a draw from `localRNG` and all LibSVM training runs under a lock …

LibLinear and LibSVM have unmanaged global RNGs

---

Common/XGBoost/src/main/java/org/tribuo/common/xgboost/XGBoostExternalModel.java
Core/src/main/java/org/tribuo/transform/TransformTrainer.java
Interop/Core/src/main/java/org/tribuo/interop/ExternalTrainerProvenance.java

Switches around how the provenance is captured in TransformTrainer so it has the right values, and updates XGBoostExternalModel so there is a way to create a model from an in-memory XGBoost `Booster`, which required an extra constructor on `ExternalTrainerProvenance`.
The transform trainer was capturing the incorrect state of the inner trainer's RNG, and the XGBoost external model creator would always throw an exception if you didn't have a valid URL to a path on disk that it could hash.

Two small fixes for provenance.

---

Core/src/main/java/org/tribuo/datasource/LibSVMDataSource.java
Core/src/test/java/org/tribuo/datasource/LibSVMDataSourceTest.java

This change normalizes the path before it is converted into a URL in LibSVMDataSource. Adds a test for the fixed behaviour.
`LibSVMDataSource.postConfig` checks to see if the URL and path are the same before throwing an exception if both are set. The `FileProvenance` constructor normalizes and absolutes the path before it is created, however the original codepath in `LibSVMDataSource` did not do this to the URL which is created. This means if the path has a relative element in it like `.` or `..` then the URL created retains the relative element and the path has it normalized out, meaning the two values are not equal and an exception is thrown when the configuration is instantiated from the provenance of a `LibSVMDataSource`.

Normalizes the URL created from paths in LibSVMDataSource

---

Classification/LibLinear/pom.xml
Classification/LibLinear/src/main/java/org/tribuo/classification/liblinear/LibLinearClassificationModel.java
Classification/LibLinear/src/test/java/org/tribuo/classification/liblinear/TestLibLinearModel.java
Classification/LibSVM/pom.xml
Classification/LibSVM/src/main/java/org/tribuo/classification/libsvm/LibSVMClassificationModel.java
Classification/LibSVM/src/main/java/org/tribuo/classification/libsvm/LibSVMClassificationTrainer.java
Classification/LibSVM/src/test/java/org/tribuo/classification/libsvm/TestLibSVM.java
Core/src/main/java/org/tribuo/onnx/ONNXAttribute.java
Core/src/main/java/org/tribuo/onnx/ONNXOperators.java
Interop/ONNX/src/main/java/org/tribuo/interop/onnx/LabelOneVOneTransformer.java
Interop/ONNX/src/main/java/org/tribuo/interop/onnx/LabelTransformer.java
Regression/LibLinear/pom.xml
Regression/LibLinear/src/main/java/org/tribuo/regression/liblinear/LibLinearRegressionModel.java
Regression/LibLinear/src/test/java/org/tribuo/regression/liblinear/TestLibLinear.java
Regression/LibSVM/pom.xml
Regression/LibSVM/src/main/java/org/tribuo/regression/libsvm/LibSVMRegressionModel.java
Regression/LibSVM/src/test/java/org/tribuo/regression/libsvm/TestLibSVM.java
tests/pom.xml
tests/src/test/java/org/tribuo/tests/onnx/EnsembleExportTest.java

Adds ONNX export support for LibLinear and LibSVM classification and regression models. It doesn't add anomaly detection export support, we'll leave that till a future release.
The LibSVM classification export depends on the exact behaviour of ONNX Runtime as the ONNX spec for SVMClassifier is incorrect - https://github.com/microsoft/onnxruntime/issues/9429.
We'd like to export models to ONNX. Also LibSVM uses an operator from the ONNX-ML set and so is a good test of the support.

ONNX export support for LibLinear and LibSVM

---

Clustering/KMeans/src/main/java/org/tribuo/clustering/kmeans/KMeansTrainer.java
Common/NearestNeighbour/src/main/java/org/tribuo/common/nearest/KNNModel.java

`KMeansTrainer` uses a `ForkJoinPool` to provide parallel computation of the e and m steps. This FJP is used even when operating in a single thread. The FJP requires extra permissions (namely "modifyThread") when running under a security manager, and in some security managers (notably OpenSearch's SecureSM) the FJP does not work at all due to a permissions issue inside OpenJDK. This means that the FJP breaks single threaded k-means training when running under a security manager, even though the FJP isn't necessary for sequential training. This change moves the FJP so it's only instantiated in multi-threaded execution paths, and also tidies up some of the code in `KMeansTrainer`. When using the FJP in `KMeansTrainer` and `KNNModel` it now uses a custom `ForkJoinWorkerThreadFactory` to …

Single threaded K-Means training no longer uses a ForkJoinPool

---

Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/ExtendedMinimumSpanningTree.java
Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanModel.java
Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanOptions.java
Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanTrainer.java
Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/TrainTest.java
Clustering/Hdbscan/src/test/java/org/tribuo/clustering/hdbscan/TestHdbscan.java
Core/src/main/java/org/tribuo/Trainer.java
spotbugs-exclude.xml

Adds the `setInvocationCount` method to `HdbscanTrainer` and tidies up a couple of small things in the HDBSCAN package.
It also enforces that the default method `Trainer.train(Dataset<T>,Map<String,Provenance>,int)` accepts -1 to mean "do not change the invocation count before training" which is the implied semantics for `INCREMENT_INVOCATION_COUNT`.
Improves integration with the reproducibility framework.

Adds setInvocationCount to HdbscanTrainer

---

Clustering/KMeans/src/main/java/org/tribuo/clustering/kmeans/KMeansModel.java
Clustering/KMeans/src/main/java/org/tribuo/clustering/kmeans/KMeansTrainer.java

Relaxed the method signatures in `KMeansTrainer` to allow the use of `DenseVector` or `SparseVector`, and changed the train & predict methods to dynamically pick between sparse and dense vectors. This is similar to the change for #112.
This speeds up k-means in dense spaces as dense vectors are faster than a sparse vector operating in a dense space.
This changes the signature of the protected `mStep` method, relaxing one of the argument types from `SparseVector[]` to `SGDVector[]`. This change means the train method will no longer call subclasses which override the `mStep` method, and so it's a breaking change for subclasses of `KMeansTrainer`. If users have tagged their override with `@Override` then the compiler will warn them and it should be a one line change.
Improves the speed of …

KMeans DenseVector support

---

README.md

Signed-off-by: Geoffrey Stewart <geoff.stewart@oracle.com>
This is a minor change which updates the Clustering section of the README.
This is just a minor documentation update.

Minor update to the README

---

Clustering/KMeans/src/main/java/org/tribuo/clustering/kmeans/KMeansTrainer.java
Clustering/KMeans/src/test/java/org/tribuo/clustering/kmeans/TestKMeans.java

Signed-off-by: Geoffrey Stewart <geoff.stewart@oracle.com>
This change adds the initialisationType value to the KMeansTrainer's toString method. 
When working with a KMeans and KMeans++ trainer in the same notebook, it is helpful to be able to see this distinction.

KMeans toString update

---

Common/NearestNeighbour/pom.xml
Common/NearestNeighbour/src/main/java/org/tribuo/common/nearest/KNNModel.java
Common/NearestNeighbour/src/test/java/org/tribuo/common/nearest/TestKNN.java

Add some basic unit tests for KNN and adjust the predict method to throw an exception as documented by the API.
Signed-off-by: Geoffrey Stewart <geoff.stewart@oracle.com>
A standard set of unit tests is being added for the k-nearest neighbor implementation
Adding these unit tests illustrates the use of this functionality and provides some checks in case there are any changes made to the KNN feature in the future.

Add some basic unit tests for KNN

---

Math/src/main/java/org/tribuo/math/neighbour/bruteforce/NeighboursBruteForce.java

Signed-off-by: Geoffrey Stewart <geoff.stewart@oracle.com>
This is a minor change that splits the existing logic into two loops rather than a single loop containing a conditional instruction.
This change makes a small optimization to the exiting logic. The changes has been extensively tested varying the size of the dataset, and the values for k.

Add the two loops variant of this min heap implementation, which is a slight optimization over the current logic

---

AnomalyDetection/Core/src/main/java/org/tribuo/anomaly/ImmutableAnomalyInfo.java
Classification/Core/src/main/java/org/tribuo/classification/ImmutableLabelInfo.java
Classification/Core/src/main/java/org/tribuo/classification/evaluation/ConfusionMatrix.java
Classification/Core/src/main/java/org/tribuo/classification/evaluation/LabelConfusionMatrix.java
Classification/Core/src/main/java/org/tribuo/classification/evaluation/LabelEvaluation.java
Classification/Core/src/main/java/org/tribuo/classification/evaluation/LabelEvaluationImpl.java
Classification/Core/src/test/java/org/tribuo/classification/evaluation/LabelConfusionMatrixTest.java
Classification/Core/src/test/java/org/tribuo/classification/evaluation/LabelEvaluatorTest.java
Clustering/Core/src/main/java/org/tribuo/clustering/ImmutableClusteringInfo.java
Core/src/main/java/org/tribuo/CategoricalIDInfo.java
Core/src/main/java/org/tribuo/CategoricalInfo.java
Core/src/main/java/org/tribuo/FeatureMap.java
Core/src/main/java/org/tribuo/ImmutableOutputInfo.java
Core/src/main/java/org/tribuo/ensemble/WeightedEnsembleModel.java
Core/src/test/java/org/tribuo/test/ImmutableMockMultiOutputInfo.java
Core/src/test/java/org/tribuo/test/MockOutputInfo.java
Data/src/main/java/org/tribuo/data/csv/CSVSaver.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/ImmutableMultiLabelInfo.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelConfusionMatrix.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelEvaluationImpl.java
MultiLabel/Core/src/test/java/org/tribuo/multilabel/evaluation/MultiLabelConfusionMatrixTest.java
Regression/Core/src/main/java/org/tribuo/regression/ImmutableRegressionInfo.java

When looking at the fix for #220 we found several other issues where Tribuo's behaviour depended on the iteration order of `HashSet`. These fell into a few categories: 
- issues where a test failed due to sorting functions being stable, but the presentation order being slightly non-deterministic (MNB, XGBoost, LinearSGD) - these were left as fixing them required changes in dependencies or intrusive changes to how predictions are generated.
- issues where the output of an evaluation `toString` depended on the label indices - these were fixed by adding/exposing methods to fix the label order, then updating the tests to use those methods.
- `WeightedEnsembleModel` assumed that the output indices of the ensemble members were the same, which in practice only affects ONNX export of ensemble …

Fixes for HashSet iteration order problems

---

Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanModel.java
Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanTrainer.java
Clustering/Hdbscan/src/test/java/org/tribuo/clustering/hdbscan/TestHdbscan.java

Adds a get method for cluster exemplars in HDBSCAN which returns copies of the exemplars (as the vector is mutable), along with a method that returns the exemplar in terms of feature names.
Fixes #217.

Exposes views on the HDBSCAN cluster exemplars

---

AnomalyDetection/LibLinear/src/main/java/org/tribuo/anomaly/liblinear/LibLinearAnomalyTrainer.java
Classification/LibLinear/src/main/java/org/tribuo/classification/liblinear/LibLinearClassificationTrainer.java
Classification/LibLinear/src/test/java/org/tribuo/classification/liblinear/TestLibLinearModel.java
Common/LibLinear/src/main/java/org/tribuo/common/liblinear/LibLinearTrainer.java
Regression/LibLinear/src/main/java/org/tribuo/regression/liblinear/LibLinearRegressionTrainer.java
Regression/LibLinear/src/test/java/org/tribuo/regression/liblinear/TestLibLinear.java
pom.xml

liblinear-java 2.44 has the fix for https://github.com/bwaldvogel/liblinear-java/issues/40, and so this PR migrates Tribuo over to use the new RNG setting methods available in that version. As a consequence it removes all the global locks on liblinear use that were in place from 4.2. This does mean that models trained in 4.2 will not reproduce exactly in 4.3+, though we could consider moving the `forceZero` trick used in the regression tests into the base class and exposing it to the reproducibility framework as a special case.
Allows liblinear models to be trained in parallel with consistent RNG behaviour as compared to the rest of Tribuo.

Bumping to liblinear-java 2.44

---

Interop/OCI/src/test/java/org/tribuo/interop/oci/OCIUtilTest.java
THIRD_PARTY_LICENSES.txt
pom.xml

Bumps OLCUT to 5.2.1 from 5.2.0.
Pick up fixes in OLCUT's dependencies.

Bumping to OLCUT 5.2.1

---

Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanTrainer.java

This change fixes an issue where clusters with small numbers of members don't have any exemplars sampled. The issue was identified by @Craigacp during some recent dev testing.
Every cluster should have at least one exemplar which can be used for predictions.

Fix for exemplars from small clusters

---

Core/src/main/java/org/tribuo/hash/HashCodeHasher.java
Core/src/main/java/org/tribuo/hash/Hasher.java
Core/src/main/java/org/tribuo/hash/MessageDigestHasher.java
Core/src/main/java/org/tribuo/hash/ModHashCodeHasher.java
Core/src/test/java/org/tribuo/hash/HasherTests.java

These changes add validations of the hash salt during object creation, either programmatically or via the Configuration System.
These changes fix #233

Validate the hash salt during object creation

---

Core/src/main/java/org/tribuo/transform/TransformedModel.java

Adds accessors to `TransformedModel` which allow access to the wrapped model, so users can call model specific methods.
Allows users to see the cluster centroids of the transformed model. Fixes #242.

Add more accessors to TransformedModel

---

Common/SGD/src/main/java/org/tribuo/common/sgd/AbstractFMModel.java
Util/ONNXExport/src/main/java/org/tribuo/util/onnx/ONNXContext.java
Util/ONNXExport/src/main/java/org/tribuo/util/onnx/ONNXOperator.java
Util/ONNXExport/src/main/java/org/tribuo/util/onnx/ONNXOperators.java
Util/ONNXExport/src/main/java/org/tribuo/util/onnx/ONNXRef.java

Introduces the `ONNXOperator` interface to allow users to insert custom ONNX ops, or ones using different opsets than opset 13 which is the base version Tribuo supports. The existing `ONNXOperators` enum now implements `ONNXOperator`, and in a future version of Tribuo we'll rename this to `ONNXOpset13` and split out the ONNX ML operators to a separate enum.
Currently Tribuo is limited to the ops available in `ONNXOperators`, this makes the ONNX model construction code insufficiently flexible.

Make the ONNX export code accept an op interface rather than the enum itself

---

Interop/ModelCard/pom.xml
tutorials/README.md
tutorials/modelcard-tribuo-v4.ipynb

Creating a tutorial to highlight the features of the ModelCard system.

Modelcard tutorial

---

THIRD_PARTY_LICENSES.txt
pom.xml

Bumps XGBoost to the latest version.
Supported versions are better.

Bumping XGBoost to 1.6.1

---

THIRD_PARTY_LICENSES.txt
pom.xml

Bumps to the latest version of the OCI Java SDK.
Newer versions are better.

Bumping to oci-java-sdk 2.38.0

---

Data/pom.xml
THIRD_PARTY_LICENSES.txt
pom.xml

Bumps to the latest version of OpenCSV.
Newer versions are better.

Bumping OpenCSV to 5.6

---

Core/src/main/java/org/tribuo/Dataset.java
Core/src/main/java/org/tribuo/ImmutableDataset.java
Core/src/main/java/org/tribuo/MutableDataset.java
Core/src/main/java/org/tribuo/dataset/MinimumCardinalityDataset.java
Core/src/main/java/org/tribuo/sequence/ImmutableSequenceDataset.java
Core/src/main/java/org/tribuo/sequence/MinimumCardinalitySequenceDataset.java
Core/src/main/java/org/tribuo/sequence/MutableSequenceDataset.java
Core/src/main/java/org/tribuo/sequence/SequenceDataset.java

Reduce redundant code by creating a `deserializeExamples` method in both `Dataset` and `SequenceDataset` classes as a protected static method that the respective impls can use instead of repeating code.  
This is a cosmetic change to simplify code maintenance by consolidating redundant code. 
This small change came out of the review for PR #264.

reduced duplicate code by creating deserializeExamples methods in

---

Classification/LibLinear/src/test/java/org/tribuo/classification/liblinear/TestLibLinearModel.java
Classification/LibSVM/src/test/java/org/tribuo/classification/libsvm/TestLibSVM.java
Classification/XGBoost/src/test/java/org/tribuo/classification/xgboost/TestXGBoost.java
Clustering/Hdbscan/src/test/java/org/tribuo/clustering/hdbscan/TestHdbscan.java
Common/NearestNeighbour/src/test/java/org/tribuo/common/nearest/TestKNN.java
Math/src/test/java/org/tribuo/math/neighbour/NeighbourQueryTestHelper.java
Math/src/test/java/org/tribuo/math/util/SGDVectorsFromCSV.java

Due to iffy URL handling to get around some Windows issues when accessing test resources a bunch of failures happen if Tribuo is checked out into a path with spaces. These are all fixed by not using Strings as an intermediate step for paths.

Fixes for test failures when running in a path with spaces in

---

Interop/OCI/pom.xml
Json/pom.xml
Reproducibility/pom.xml
THIRD_PARTY_LICENSES.txt
distribution/pom.xml
pom.xml

We want to use the latest versions of these things.

Bumping versions of XGBoost, jackson, protobuf and OCI

---

build_spec.yaml

Add build_spec.yaml
This prepares the repository for Oracle's GitHub repository guideline checks

Add build_spec.yaml as a preparation for Oracle's GitHub repository guideline checks

---

Classification/Core/src/main/java/org/tribuo/classification/sequence/viterbi/ViterbiModel.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/ClassifierChainModel.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/IndependentMultiLabelModel.java
MultiLabel/Core/src/main/java/org/tribuo/multilabel/baseline/IndependentMultiLabelTrainer.java

Adds accessors for the models which comprise a classifier chain or a binary relevance multilabel model.
Model access is useful for inspecting the inner models. Fixes #300.

Adding accessors to ClassifierChainModel and IndependentMultiLabelModel

---

Core/src/main/java/org/tribuo/Example.java
Core/src/main/java/org/tribuo/impl/ArrayExample.java
Core/src/main/java/org/tribuo/impl/IndexedArrayExample.java
Core/src/main/java/org/tribuo/impl/ListExample.java
Core/src/test/java/org/tribuo/ExampleTest.java

`Example.densify(List<String>)` behaved incorrectly if the list did not contain the feature names already present in the example. This PR fixes it so densify always adds zero valued features for any feature names not present in the example.
Fixes #299.

Fixing Example.densify

---

THIRD_PARTY_LICENSES.txt
pom.xml

Update dependencies in `main` branch. These bumps have already happened in the 4.2 and 4.3 release branches.
Newer versions have fewer known CVEs.

Bumping OpenCSV to 5.7.1 and jackson to 2.14.1

---

README.md
docs/release-notes/tribuo-v4-3-1-release-notes.md

Cherry-picks the release notes for v4.3.1 across to `main`.

Adding v4.3.1 release notes to main branch

---

Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanTrainer.java
Data/src/main/java/org/tribuo/data/text/DirectoryFileSource.java
Data/src/main/java/org/tribuo/data/text/impl/SimpleStringDataSource.java
Data/src/main/java/org/tribuo/data/text/impl/SimpleTextDataSource.java
Data/src/test/java/org/tribuo/data/text/impl/SimpleStringDataSourceTest.java

`DirectoryFileSource`, `SimpleStringDataSource` and `SimpleTextDataSource` all failed to call `super.getInstanceValues()` and so missed some values when converted into marshalled provenances. This PR relaxes the check for existing protobufs (as the missing value is a constant) and fixes `getInstanceValues` for these classes so it is correctly marshalled in the future. It also properly serializes `ClusterExemplar`s from v4.2 which may contain null values.
Protobuf serialization will be the only supported form in v5.

Fixes for protobuf creation in a few classes

---

Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanOptions.java
Clustering/Hdbscan/src/main/java/org/tribuo/clustering/hdbscan/HdbscanTrainer.java
Clustering/Hdbscan/src/test/java/org/tribuo/clustering/hdbscan/TestHdbscan.java

We need to improve the determination of cluster exemplars, which are used after the model is trained to make predictions. Some cases, such as those which use contrived datasets, can result in very "clean" clusters, with no outliers. One such case has exposed an issue in the current logic to determine cluster exemplars. The seed, which is used when sampling cluster exemplars at random from members of a cluster, is exposed as a config parameter.
This change fixes #355 on the main branch.

Improve the determination of cluster exemplars fix for main

---

Interop/OCI/pom.xml
Interop/OCI/src/main/java/org/tribuo/interop/oci/OCIModel.java
Interop/OCI/src/main/java/org/tribuo/interop/oci/OCIModelCLI.java
Interop/OCI/src/main/java/org/tribuo/interop/oci/OCIUtil.java
THIRD_PARTY_LICENSES.txt
pom.xml

Bumped to the latest version of the OCI Java SDK.
The OCI SDK version was very old.

Bumping to OCI Java SDK 3.37.0

---

.github/workflows/maven-macos-aarch64.yml
.github/workflows/maven-macos-x64.yml
.github/workflows/maven-windows.yml

Adds the newly released JDK 22 to the CI and also ads a macOS aarch64 runner.
We test on LTS JDKs from 17 onwards along with the latest release. Also more development is moving to macOS aarch64 and there are now free Github runners for it.

Adding JDK 22 and a macOS aarch64 runner to the CI

---

Core/src/main/java/org/tribuo/Dataset.java
Core/src/main/java/org/tribuo/dataset/DatasetView.java

`Dataset.createTransformers` incorrectly iterated `Dataset.data` rather than using the dataset iterator. As the dataset iterator is overridden in `DatasetView` but the data array is empty this caused the transformation to be fit incorrectly and the feature values to be corrupted. 
The fix causes `Dataset.createTransformers` to use `Dataset.size()` and `Dataset.iterator()` both of which can be overridden. The PR also includes two additional fixes for `DatasetView` behaviour as shuffling was incorrect because it could return data points that weren't in the view, and the provenance recorded the wrong indices (it was tracking the shuffle indices not the indices selected for the view). I think this covers all direct uses of `Dataset.data` so they now are routed through the proper methods.
This …

Dataset.createTransformers fix for DatasetView/TransformTrainer

---

Interop/OCI/pom.xml
THIRD_PARTY_LICENSES.txt
pom.xml

Bump several dependencies to the latest versions.
Use supported versions of the dependencies.

Dependency bump

---

Util/Tokenization/src/main/java/org/tribuo/util/tokens/impl/wordpiece/WordpieceTokenizer.java

WordpieceTokenizer improperly cloned it's state, so failed in multithreaded environments. Now it doesn't.
Fewer crashes.

Fixing a multithreading bug in WordpieceTokenizer

---

Common/Trees/src/main/java/org/tribuo/common/tree/impl/IntArrayContainer.java
Common/Trees/src/test/java/org/tribuo/common/tree/impl/IntArrayContainerTest.java
Regression/RegressionTree/src/test/java/org/tribuo/regression/rtree/TestCARTJointRegressionTrainer.java
Regression/RegressionTree/src/test/java/org/tribuo/regression/rtree/TestCARTRegressionTrainer.java
Regression/RegressionTree/src/test/java/org/tribuo/regression/rtree/TestRegressionEnsembles.java

The merge method should not duplicate inputs, which can lead to issues in the regression trees which use that method.
Fix for #383 and more tests for `IntArrayContainer`.

Fixing a bug in IntArrayContainer.merge and adding tests

---

Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/TensorFlowCheckpointModel.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/TensorFlowFrozenExternalModel.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/TensorFlowModel.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/TensorFlowNativeModel.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/TensorFlowSavedModelExternalModel.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/TensorFlowTrainer.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/example/CNNExamples.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/example/GraphDefTuple.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/example/MLPExamples.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/sequence/TensorFlowSequenceModel.java
Interop/Tensorflow/src/main/java/org/tribuo/interop/tensorflow/sequence/TensorFlowSequenceTrainer.java
Interop/Tensorflow/src/test/java/org/tribuo/interop/tensorflow/ClassificationTest.java
THIRD_PARTY_LICENSES.txt
pom.xml

Bumps Tribuo's TF interop to TF-Java 1.0.0-rc1 for testing. This release adds macOS ARM64 binaries and has a fix for the training gradient issue.
Run the CI against the new release candidate.

Moving to TF-Java 1.0.0
